//Maya ASCII 2022 scene
//Name: lambert8SG.ma
//Last modified: Mon, Oct 28, 2024 07:18:50 PM
//Codeset: 1252
requires maya "2022";
requires "stereoCamera" "10.0";
requires "mtoa" "4.2.1";
requires "stereoCamera" "10.0";
currentUnit -l centimeter -a degree -t film;
fileInfo "application" "maya";
fileInfo "product" "Maya 2022";
fileInfo "version" "2022";
fileInfo "cutIdentifier" "202102181415-29bfc1879c";
fileInfo "osv" "Windows 10 Home v2009 (Build: 19045)";
fileInfo "UUID" "B7C2C685-4059-92E5-56D5-6EB2828534FA";
createNode shadingEngine -n "lambert8SG";
	rename -uid "98F0C986-478A-9751-2BDD-799691ACBD04";
	setAttr ".ihi" 0;
	setAttr -s 9 ".dsm";
	setAttr ".ro" yes;
createNode materialInfo -n "materialInfo16";
	rename -uid "6A727BCE-49E4-CE59-8A68-8F81303A479C";
createNode lambert -n "grey";
	rename -uid "9BE5FBBD-4EB1-32F1-A90D-D3B37B35A30D";
	setAttr ".c" -type "float3" 0.14723909 0.13798742 0.18110721 ;
createNode lightLinker -s -n "lightLinker1";
	rename -uid "A9275823-4B9B-5317-AE82-05BC62B83FDB";
	setAttr -s 27 ".lnk";
	setAttr -s 27 ".slnk";
select -ne :time1;
	setAttr ".o" 1;
	setAttr ".unw" 1;
select -ne :hardwareRenderingGlobals;
	setAttr ".otfna" -type "stringArray" 22 "NURBS Curves" "NURBS Surfaces" "Polygons" "Subdiv Surface" "Particles" "Particle Instance" "Fluids" "Strokes" "Image Planes" "UI" "Lights" "Cameras" "Locators" "Joints" "IK Handles" "Deformers" "Motion Trails" "Components" "Hair Systems" "Follicles" "Misc. UI" "Ornaments"  ;
	setAttr ".otfva" -type "Int32Array" 22 0 1 1 1 1 1
		 1 1 1 0 0 0 0 0 0 0 0 0
		 0 0 0 0 ;
	setAttr ".fprt" yes;
select -ne :renderPartition;
	setAttr -s 27 ".st";
select -ne :renderGlobalsList1;
select -ne :defaultShaderList1;
	setAttr -s 30 ".s";
select -ne :postProcessList1;
	setAttr -s 2 ".p";
select -ne :defaultRenderUtilityList1;
	setAttr -s 23 ".u";
select -ne :defaultRenderingList1;
select -ne :defaultTextureList1;
	setAttr -s 19 ".tx";
select -ne :initialShadingGroup;
	setAttr -s 11 ".dsm";
	setAttr ".ro" yes;
select -ne :initialParticleSE;
	setAttr ".ro" yes;
select -ne :defaultRenderGlobals;
	setAttr ".ren" -type "string" "arnold";
select -ne :defaultResolution;
	setAttr ".pa" 1;
select -ne :defaultColorMgtGlobals;
	setAttr ".cfe" yes;
	setAttr ".cfp" -type "string" "<MAYA_RESOURCES>/OCIO-configs/Maya2022-default/config.ocio";
	setAttr ".wsn" -type "string" "ACEScg";
select -ne :hardwareRenderGlobals;
	setAttr ".ctrs" 256;
	setAttr ".btrs" 512;
select -ne :ikSystem;
	setAttr -s 4 ".sol";
connectAttr "grey.oc" "lambert8SG.ss";
connectAttr "TANKShape.iog" "lambert8SG.dsm" -na;
connectAttr "LEG_MID_RShape.iog" "lambert8SG.dsm" -na;
connectAttr "FOREARM_LShape.iog" "lambert8SG.dsm" -na;
connectAttr "FOOT_1_LShape.iog" "lambert8SG.dsm" -na;
connectAttr "LEG_MID_LShape.iog" "lambert8SG.dsm" -na;
connectAttr "FOOT_1_RShape.iog" "lambert8SG.dsm" -na;
connectAttr "L_ARM_DOWNShape.iog" "lambert8SG.dsm" -na;
connectAttr "L_ARM_UPShape.iog" "lambert8SG.dsm" -na;
connectAttr "BELTShape.iog" "lambert8SG.dsm" -na;
connectAttr "lambert8SG.msg" "materialInfo16.sg";
connectAttr "grey.msg" "materialInfo16.m";
relationship "link" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" "lambert8SG.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" "lambert8SG.message" ":defaultLightSet.message";
connectAttr "lambert8SG.pa" ":renderPartition.st" -na;
connectAttr "grey.msg" ":defaultShaderList1.s" -na;
// End of lambert8SG.ma
