//Maya ASCII 2022 scene
//Name: lambert4SG.ma
//Last modified: Mon, Oct 28, 2024 07:18:49 PM
//Codeset: 1252
requires maya "2022";
requires "stereoCamera" "10.0";
requires "mtoa" "4.2.1";
requires "stereoCamera" "10.0";
currentUnit -l centimeter -a degree -t film;
fileInfo "application" "maya";
fileInfo "product" "Maya 2022";
fileInfo "version" "2022";
fileInfo "cutIdentifier" "202102181415-29bfc1879c";
fileInfo "osv" "Windows 10 Home v2009 (Build: 19045)";
fileInfo "UUID" "A55A2024-4500-25C3-8E5C-40B807B07DD4";
createNode shadingEngine -n "lambert4SG";
	rename -uid "95E428E4-4428-49BA-253C-C286912B6EED";
	setAttr ".ihi" 0;
	setAttr -s 8 ".dsm";
	setAttr ".ro" yes;
createNode materialInfo -n "materialInfo12";
	rename -uid "CD0D9388-459C-C0A7-AD51-8D9004BBAE8F";
createNode lambert -n "blue";
	rename -uid "DC44F1AB-42C6-748B-1A9E-138FB5518273";
	setAttr ".c" -type "float3" 0.44461343 5.5864754 1.755633 ;
createNode lightLinker -s -n "lightLinker1";
	rename -uid "A9275823-4B9B-5317-AE82-05BC62B83FDB";
	setAttr -s 27 ".lnk";
	setAttr -s 27 ".slnk";
select -ne :time1;
	setAttr ".o" 1;
	setAttr ".unw" 1;
select -ne :hardwareRenderingGlobals;
	setAttr ".otfna" -type "stringArray" 22 "NURBS Curves" "NURBS Surfaces" "Polygons" "Subdiv Surface" "Particles" "Particle Instance" "Fluids" "Strokes" "Image Planes" "UI" "Lights" "Cameras" "Locators" "Joints" "IK Handles" "Deformers" "Motion Trails" "Components" "Hair Systems" "Follicles" "Misc. UI" "Ornaments"  ;
	setAttr ".otfva" -type "Int32Array" 22 0 1 1 1 1 1
		 1 1 1 0 0 0 0 0 0 0 0 0
		 0 0 0 0 ;
	setAttr ".fprt" yes;
select -ne :renderPartition;
	setAttr -s 27 ".st";
select -ne :renderGlobalsList1;
select -ne :defaultShaderList1;
	setAttr -s 30 ".s";
select -ne :postProcessList1;
	setAttr -s 2 ".p";
select -ne :defaultRenderUtilityList1;
	setAttr -s 23 ".u";
select -ne :defaultRenderingList1;
select -ne :defaultTextureList1;
	setAttr -s 19 ".tx";
select -ne :initialShadingGroup;
	setAttr -s 11 ".dsm";
	setAttr ".ro" yes;
select -ne :initialParticleSE;
	setAttr ".ro" yes;
select -ne :defaultRenderGlobals;
	setAttr ".ren" -type "string" "arnold";
select -ne :defaultResolution;
	setAttr ".pa" 1;
select -ne :defaultColorMgtGlobals;
	setAttr ".cfe" yes;
	setAttr ".cfp" -type "string" "<MAYA_RESOURCES>/OCIO-configs/Maya2022-default/config.ocio";
	setAttr ".wsn" -type "string" "ACEScg";
select -ne :hardwareRenderGlobals;
	setAttr ".ctrs" 256;
	setAttr ".btrs" 512;
select -ne :ikSystem;
	setAttr -s 4 ".sol";
connectAttr "blue.oc" "lambert4SG.ss";
connectAttr "HAND_ARMORShape.iog" "lambert4SG.dsm" -na;
connectAttr "GLOWSTICK_RShape.iog" "lambert4SG.dsm" -na;
connectAttr "VISORShape.iog" "lambert4SG.dsm" -na;
connectAttr "GLOWSTICK_LShape.iog" "lambert4SG.dsm" -na;
connectAttr "BOOST2_RShape.iog" "lambert4SG.dsm" -na;
connectAttr "BOOST1_RShape.iog" "lambert4SG.dsm" -na;
connectAttr "BOOST1_LShape.iog" "lambert4SG.dsm" -na;
connectAttr "BOOST2_LShape.iog" "lambert4SG.dsm" -na;
connectAttr "lambert4SG.msg" "materialInfo12.sg";
connectAttr "blue.msg" "materialInfo12.m";
relationship "link" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" "lambert4SG.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" "lambert4SG.message" ":defaultLightSet.message";
connectAttr "lambert4SG.pa" ":renderPartition.st" -na;
connectAttr "blue.msg" ":defaultShaderList1.s" -na;
// End of lambert4SG.ma
