//Maya ASCII 2022 scene
//Name: lambert5SG.ma
//Last modified: Mon, Oct 28, 2024 07:18:51 PM
//Codeset: 1252
requires maya "2022";
requires "stereoCamera" "10.0";
requires "mtoa" "4.2.1";
requires "stereoCamera" "10.0";
currentUnit -l centimeter -a degree -t film;
fileInfo "application" "maya";
fileInfo "product" "Maya 2022";
fileInfo "version" "2022";
fileInfo "cutIdentifier" "202102181415-29bfc1879c";
fileInfo "osv" "Windows 10 Home v2009 (Build: 19045)";
fileInfo "UUID" "EEC42B5B-41F5-C2E5-00A4-C5BF92690185";
createNode shadingEngine -n "lambert5SG";
	rename -uid "8B342A46-43DA-1BD3-6D04-01BDE93807EB";
	setAttr ".ihi" 0;
	setAttr -s 20 ".dsm";
	setAttr ".ro" yes;
createNode materialInfo -n "materialInfo13";
	rename -uid "4E705138-4945-ED33-EF53-F2BA5135B96F";
createNode lambert -n "hotpink";
	rename -uid "DF74E10A-44C6-E850-A52E-1086EFC5FD03";
	setAttr ".c" -type "float3" 0.67472911 0.15972194 0.51498777 ;
createNode lightLinker -s -n "lightLinker1";
	rename -uid "A9275823-4B9B-5317-AE82-05BC62B83FDB";
	setAttr -s 27 ".lnk";
	setAttr -s 27 ".slnk";
select -ne :time1;
	setAttr ".o" 1;
	setAttr ".unw" 1;
select -ne :hardwareRenderingGlobals;
	setAttr ".otfna" -type "stringArray" 22 "NURBS Curves" "NURBS Surfaces" "Polygons" "Subdiv Surface" "Particles" "Particle Instance" "Fluids" "Strokes" "Image Planes" "UI" "Lights" "Cameras" "Locators" "Joints" "IK Handles" "Deformers" "Motion Trails" "Components" "Hair Systems" "Follicles" "Misc. UI" "Ornaments"  ;
	setAttr ".otfva" -type "Int32Array" 22 0 1 1 1 1 1
		 1 1 1 0 0 0 0 0 0 0 0 0
		 0 0 0 0 ;
	setAttr ".fprt" yes;
select -ne :renderPartition;
	setAttr -s 27 ".st";
select -ne :renderGlobalsList1;
select -ne :defaultShaderList1;
	setAttr -s 30 ".s";
select -ne :postProcessList1;
	setAttr -s 2 ".p";
select -ne :defaultRenderUtilityList1;
	setAttr -s 23 ".u";
select -ne :defaultRenderingList1;
select -ne :defaultTextureList1;
	setAttr -s 19 ".tx";
select -ne :initialShadingGroup;
	setAttr -s 11 ".dsm";
	setAttr ".ro" yes;
select -ne :initialParticleSE;
	setAttr ".ro" yes;
select -ne :defaultRenderGlobals;
	setAttr ".ren" -type "string" "arnold";
select -ne :defaultResolution;
	setAttr ".pa" 1;
select -ne :defaultColorMgtGlobals;
	setAttr ".cfe" yes;
	setAttr ".cfp" -type "string" "<MAYA_RESOURCES>/OCIO-configs/Maya2022-default/config.ocio";
	setAttr ".wsn" -type "string" "ACEScg";
select -ne :hardwareRenderGlobals;
	setAttr ".ctrs" 256;
	setAttr ".btrs" 512;
select -ne :ikSystem;
	setAttr -s 4 ".sol";
connectAttr "hotpink.oc" "lambert5SG.ss";
connectAttr "LEG_DOWN_LShape.iog" "lambert5SG.dsm" -na;
connectAttr "LEG_UP_LShape.iog" "lambert5SG.dsm" -na;
connectAttr "FOOT_3_LShape.iog" "lambert5SG.dsm" -na;
connectAttr "HAND_RShape.iog" "lambert5SG.dsm" -na;
connectAttr "LEG_DOWN_RShape.iog" "lambert5SG.dsm" -na;
connectAttr "COMS_COVERShape.iog" "lambert5SG.dsm" -na;
connectAttr "FOOT_3_RShape.iog" "lambert5SG.dsm" -na;
connectAttr "BUCKLEShape.iog" "lambert5SG.dsm" -na;
connectAttr "KNEEPADD_LShape.iog" "lambert5SG.dsm" -na;
connectAttr "LEG_UP_RShape.iog" "lambert5SG.dsm" -na;
connectAttr "FOOT_2_LShape.iog" "lambert5SG.dsm" -na;
connectAttr "HAND_ARMOR_1Shape.iog" "lambert5SG.dsm" -na;
connectAttr "KNEEPAD_RShape.iog" "lambert5SG.dsm" -na;
connectAttr "HAND_ARMOR_3Shape.iog" "lambert5SG.dsm" -na;
connectAttr "HELMETShape.iog" "lambert5SG.dsm" -na;
connectAttr "FOOT_2_RShape.iog" "lambert5SG.dsm" -na;
connectAttr "HAND_ARMOR_4Shape.iog" "lambert5SG.dsm" -na;
connectAttr "HAND_ARMOR_2Shape.iog" "lambert5SG.dsm" -na;
connectAttr "HAND_LShape.iog" "lambert5SG.dsm" -na;
connectAttr "FOREARM_ARMOR_RShape.iog" "lambert5SG.dsm" -na;
connectAttr "lambert5SG.msg" "materialInfo13.sg";
connectAttr "hotpink.msg" "materialInfo13.m";
relationship "link" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" "lambert5SG.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" "lambert5SG.message" ":defaultLightSet.message";
connectAttr "lambert5SG.pa" ":renderPartition.st" -na;
connectAttr "hotpink.msg" ":defaultShaderList1.s" -na;
// End of lambert5SG.ma
