//Maya ASCII 2022 scene
//Name: lambert6SG.ma
//Last modified: Sun, Oct 27, 2024 03:49:52 AM
//Codeset: 1252
requires maya "2022";
requires "stereoCamera" "10.0";
requires "mtoa" "4.2.1";
currentUnit -l centimeter -a degree -t film;
fileInfo "application" "maya";
fileInfo "product" "Maya 2022";
fileInfo "version" "2022";
fileInfo "cutIdentifier" "202102181415-29bfc1879c";
fileInfo "osv" "Windows 10 Home v2009 (Build: 19045)";
fileInfo "UUID" "C7C64488-42DD-78D1-5300-F6B55C0DCFC7";
createNode shadingEngine -n "lambert6SG";
	rename -uid "3B6E17CE-4C36-22DF-D668-5FAC43BACF06";
	setAttr ".ihi" 0;
	setAttr -s 10 ".dsm";
	setAttr ".ro" yes;
createNode materialInfo -n "materialInfo14";
	rename -uid "8252B0A1-49FC-FF3C-9976-9A87982D6C22";
createNode lambert -n "prup";
	rename -uid "E70B971D-41F1-6536-0435-B29287233664";
	setAttr ".c" -type "float3" 0.17675586 0.11602238 0.22835456 ;
createNode lightLinker -s -n "lightLinker1";
	rename -uid "F378836A-4A36-B62C-509D-C99C1911BAA6";
	setAttr -s 27 ".lnk";
	setAttr -s 27 ".slnk";
select -ne :time1;
	setAttr ".o" 1;
	setAttr ".unw" 1;
select -ne :hardwareRenderingGlobals;
	setAttr ".otfna" -type "stringArray" 22 "NURBS Curves" "NURBS Surfaces" "Polygons" "Subdiv Surface" "Particles" "Particle Instance" "Fluids" "Strokes" "Image Planes" "UI" "Lights" "Cameras" "Locators" "Joints" "IK Handles" "Deformers" "Motion Trails" "Components" "Hair Systems" "Follicles" "Misc. UI" "Ornaments"  ;
	setAttr ".otfva" -type "Int32Array" 22 0 1 1 1 1 1
		 1 1 1 0 0 0 0 0 0 0 0 0
		 0 0 0 0 ;
	setAttr ".fprt" yes;
select -ne :renderPartition;
	setAttr -s 27 ".st";
select -ne :renderGlobalsList1;
select -ne :defaultShaderList1;
	setAttr -s 30 ".s";
select -ne :postProcessList1;
	setAttr -s 2 ".p";
select -ne :defaultRenderUtilityList1;
	setAttr -s 23 ".u";
select -ne :defaultRenderingList1;
select -ne :defaultTextureList1;
	setAttr -s 19 ".tx";
select -ne :initialShadingGroup;
	setAttr -s 11 ".dsm";
	setAttr ".ro" yes;
select -ne :initialParticleSE;
	setAttr ".ro" yes;
select -ne :defaultRenderGlobals;
	setAttr ".ren" -type "string" "arnold";
select -ne :defaultResolution;
	setAttr ".pa" 1;
select -ne :defaultColorMgtGlobals;
	setAttr ".cfe" yes;
	setAttr ".cfp" -type "string" "<MAYA_RESOURCES>/OCIO-configs/Maya2022-default/config.ocio";
	setAttr ".wsn" -type "string" "ACEScg";
select -ne :hardwareRenderGlobals;
	setAttr ".ctrs" 256;
	setAttr ".btrs" 512;
select -ne :ikSystem;
	setAttr -s 4 ".sol";
select -ne :modelPanel4ViewSelectedSet;
	setAttr ".ihi" 0;
connectAttr "prup.oc" "lambert6SG.ss";
connectAttr "LEG_MID_LShape.iog" "lambert6SG.dsm" -na;
connectAttr "LEG_MID_RShape.iog" "lambert6SG.dsm" -na;
connectAttr "FOOT_1_LShape.iog" "lambert6SG.dsm" -na;
connectAttr "FOOT_1_RShape.iog" "lambert6SG.dsm" -na;
connectAttr "BACKPACKShape.iog" "lambert6SG.dsm" -na;
connectAttr "TANKShape.iog" "lambert6SG.dsm" -na;
connectAttr "L_ARM_DOWNShape.iog" "lambert6SG.dsm" -na;
connectAttr "FOREARM_LShape.iog" "lambert6SG.dsm" -na;
connectAttr "L_ARM_UPShape.iog" "lambert6SG.dsm" -na;
connectAttr "BELTShape.iog" "lambert6SG.dsm" -na;
connectAttr "lambert6SG.msg" "materialInfo14.sg";
connectAttr "prup.msg" "materialInfo14.m";
relationship "link" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" "lambert6SG.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" "lambert6SG.message" ":defaultLightSet.message";
connectAttr "lambert6SG.pa" ":renderPartition.st" -na;
connectAttr "prup.msg" ":defaultShaderList1.s" -na;
// End of lambert6SG.ma
